# Site settings
title: Abdulrahmen Almodaimegh      # This is your site's title, used in the browser tab and header
email: abdul.almod@gmail.com         # Your contact email
description: >-                      # The >- symbol allows for multiline text
  A portfolio and blog about mathematics, computer graphics,
  and programming insights.          # This description appears in search results and metadata

baseurl: ""                         # Used when your site lives in a subdirectory. Empty for username.github.io sites
url: "https://abdul-nosirrom.github.io"  # Your site's full URL

github_username: abdul-nosirrom
linkedin_username: abdulrahmen-al-modaimegh-758bbb22b
twitter_username: FlexMentall0

# Build settings
markdown: kramdown                  # Specifies the Markdown processor
kramdown:                          # Kramdown-specific settings
  math_engine: katex               # Uses KaTeX for math rendering
  syntax_highlighter: null        # Code syntax highlighting (null because we'll use prism.js not rouge)
  syntax_highlighter_opts:
    disable: true

# Collections configuration
collections:                       # Defines different types of content
  projects:                       # Your projects collection
    output: true                  # Creates individual pages for each project
    permalink: /projects/:path/   # URL structure for project pages
  posts:                         # Note: 'posts' is usually automatic in Jekyll
    output: true                 # This is redundant as posts are always output
    permalink: /posts/:path/     # URL structure for blog posts

# Default front matter settings
defaults:                        # Automatically applies these settings to files
  - scope:                      # First scope block for posts
      path: ""                  # Applies to all files in the project
      type: "posts"            # But only of type "posts"
    values:                     # Values to apply
      layout: "post"           # Use post.html layout
      comments: true           # Enable comments
  - scope:                     # Second scope block for projects
      path: ""
      type: "projects"
    values:
      layout: "project"        # Use project.html layout
  - scope:                     # Third scope block for pages
      path: ""
      type: "pages"
    values:
      layout: "default"        # Use default.html layout

# Plugin settings
plugins:                       # Jekyll plugins to enable
  - jekyll-paginate           # For pagination
  - jekyll-sitemap            # Generates sitemap
  - jekyll-feed               # Generates RSS feed
  - jekyll-seo-tag           # For SEO optimization
  - jekyll-gfm               # GitHub Flavored Markdown

# Pagination settings
paginate: 6                   # Number of posts per page
paginate_path: "/posts/page:num/"  # Note: This conflicts with your posts permalink
                                  # Consider changing to "/posts/page:num/"

# Sass settings
sass:
  sass_dir: _sass             # Where Sass files are stored
  style: compressed          # Minifies the CSS output

# Exclude files
exclude:                     # Files/folders to ignore when building site
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - README.md